from enum import IntEnum

class Categorie(IntEnum):
    CODE = 0
    MATH = 1
    RAG = 2
    CONVERSATION = 3
    AUTRE = 4


# Ajouter ici les paires generees ou corrigees par un humain.
EXEMPLES = [
    # Code
    ("aide-moi a corriger ce bug", Categorie.CODE),
    ("pourquoi mon programme Python plante-t-il ?", Categorie.CODE),
    ("ecris une fonction pour trier une liste", Categorie.CODE),
    ("comment ajouter une route dans mon API ?", Categorie.CODE),
    ("explique cette erreur TypeScript", Categorie.CODE),
    ("mon script ne demarre pas", Categorie.CODE),
    ("comment lire un fichier JSON en Python ?", Categorie.CODE),
    ("cree une classe utilisateur en Java", Categorie.CODE),
    ("pourquoi cette requete SQL echoue ?", Categorie.CODE),
    ("ajoute des tests unitaires a ce module", Categorie.CODE),
    ("comment faire une boucle en JavaScript ?", Categorie.CODE),
    ("mon composant React ne se met pas a jour", Categorie.CODE),
    ("explique-moi cette stack trace", Categorie.CODE),
    ("convertis cette fonction en async await", Categorie.CODE),
    ("comment installer une dependance npm ?", Categorie.CODE),
    ("ecris une expression reguliere pour un email", Categorie.CODE),
    ("pourquoi mon endpoint retourne une erreur 500 ?", Categorie.CODE),
    ("aide-moi a configurer Docker", Categorie.CODE),
    ("comment fusionner deux dictionnaires Python ?", Categorie.CODE),
    ("ce code a une fuite memoire", Categorie.CODE),
    ("genere une migration de base de donnees", Categorie.CODE),
    ("comment utiliser git rebase ?", Categorie.CODE),
    ("mon build CI est en echec", Categorie.CODE),
    ("ecris une requete GraphQL", Categorie.CODE),
    ("comment declarer une variable en Rust ?", Categorie.CODE),
    ("optimise cette fonction lente", Categorie.CODE),
    ("pourquoi mon CSS ne s applique pas ?", Categorie.CODE),
    ("ajoute une authentification JWT", Categorie.CODE),
    ("comment appeler cette API REST ?", Categorie.CODE),
    ("explique les generics en TypeScript", Categorie.CODE),
    ("ecris un script bash de sauvegarde", Categorie.CODE),
    ("mon test pytest ne trouve pas le module", Categorie.CODE),
    ("comment parser du XML en Python ?", Categorie.CODE),
    ("corrige cette erreur de syntaxe", Categorie.CODE),
    ("cree un formulaire avec validation", Categorie.CODE),
    ("comment paginer les resultats SQL ?", Categorie.CODE),
    ("mon serveur Node ecoute sur le mauvais port", Categorie.CODE),
    ("ecris une fonction de hachage", Categorie.CODE),
    ("comment deployer mon application ?", Categorie.CODE),
    ("aide-moi a comprendre ce code", Categorie.CODE),

    # Math
    ("que vaut 6 * 7 ?", Categorie.MATH),
    ("calcule la racine carree de 144", Categorie.MATH),
    ("additionne 18 et 24", Categorie.MATH),
    ("comment resoudre cette equation ?", Categorie.MATH),
    ("quel est le resultat de 12 % 5 ?", Categorie.MATH),
    ("combien font 125 plus 78 ?", Categorie.MATH),
    ("resous 3x + 4 = 19", Categorie.MATH),
    ("calcule 15 pour cent de 240", Categorie.MATH),
    ("quelle est l aire d un cercle de rayon 5 ?", Categorie.MATH),
    ("multiplie 37 par 12", Categorie.MATH),
    ("convertis 0,75 en fraction", Categorie.MATH),
    ("quel est le PGCD de 24 et 36 ?", Categorie.MATH),
    ("trouve la derivee de x carre", Categorie.MATH),
    ("integre 2x entre 0 et 3", Categorie.MATH),
    ("combien y a-t-il de secondes dans 3 heures ?", Categorie.MATH),
    ("calcule la moyenne de 12, 15 et 18", Categorie.MATH),
    ("resous le systeme x + y = 10 et x - y = 2", Categorie.MATH),
    ("quelle est la probabilite de tirer pile ?", Categorie.MATH),
    ("simplifie la fraction 42 sur 56", Categorie.MATH),
    ("combien font 9 puissance 3 ?", Categorie.MATH),
    ("trouve le perimetre d un rectangle 8 par 3", Categorie.MATH),
    ("calcule 1,2 divise par 0,4", Categorie.MATH),
    ("quel est le reste de 29 divise par 6 ?", Categorie.MATH),
    ("resous x carre - 9 = 0", Categorie.MATH),
    ("calcule le volume d un cube de cote 4", Categorie.MATH),
    ("convertis 45 degres en radians", Categorie.MATH),
    ("quelle est la somme des angles d un triangle ?", Categorie.MATH),
    ("combien font 7 huitiemes plus 3 huitiemes ?", Categorie.MATH),
    ("trouve la mediane de 3, 7, 9, 10, 15", Categorie.MATH),
    ("calcule les interets de 1000 euros a 5 pour cent", Categorie.MATH),
    ("developpe (x + 2) au carre", Categorie.MATH),
    ("factorise x carre + 5x + 6", Categorie.MATH),
    ("combien de diagonales a un hexagone ?", Categorie.MATH),
    ("calcule la distance entre les points 0,0 et 3,4", Categorie.MATH),
    ("quelle est la valeur absolue de moins 17 ?", Categorie.MATH),
    ("trouve 20 pour cent de reduction sur 80 euros", Categorie.MATH),
    ("calcule le logarithme de 100 en base 10", Categorie.MATH),
    ("resous 2x = 14", Categorie.MATH),
    ("combien font 999 moins 456 ?", Categorie.MATH),
    ("calcule 4 factorielle", Categorie.MATH),

    # RAG
    ("resume de ce document", Categorie.RAG),
    ("cherche cette information dans la documentation", Categorie.RAG),
    ("quels passages parlent de securite dans ce fichier ?", Categorie.RAG),
    ("reponds a partir de la base de connaissances", Categorie.RAG),
    ("extrais les points importants de ce contrat", Categorie.RAG),
    ("retrouve la politique de remboursement dans le guide", Categorie.RAG),
    ("fais un resume du PDF joint", Categorie.RAG),
    ("que dit le manuel sur les sauvegardes ?", Categorie.RAG),
    ("cherche le nom du responsable dans ce document", Categorie.RAG),
    ("compare les deux versions de cette procedure", Categorie.RAG),
    ("trouve la date limite dans le contrat", Categorie.RAG),
    ("liste les exigences mentionnees dans le cahier des charges", Categorie.RAG),
    ("releve les risques indiques dans ce rapport", Categorie.RAG),
    ("ou est explique le processus de validation ?", Categorie.RAG),
    ("cite le passage sur la confidentialite", Categorie.RAG),
    ("synthese de la reunion a partir des notes", Categorie.RAG),
    ("quelle est la procedure de connexion selon le wiki ?", Categorie.RAG),
    ("cherche les informations sur le produit Alpha", Categorie.RAG),
    ("reponds en utilisant uniquement les documents fournis", Categorie.RAG),
    ("extrais toutes les dates de ce texte", Categorie.RAG),
    ("quels sont les objectifs du projet dans la presentation ?", Categorie.RAG),
    ("trouve les conditions d annulation dans les CGV", Categorie.RAG),
    ("resume le chapitre trois du manuel", Categorie.RAG),
    ("dans quel fichier se trouve la configuration ?", Categorie.RAG),
    ("que recommande la documentation interne ?", Categorie.RAG),
    ("liste les actions a faire dans ce compte rendu", Categorie.RAG),
    ("cherche les references legales citees dans le dossier", Categorie.RAG),
    ("explique ce que dit la base documentaire sur les incidents", Categorie.RAG),
    ("retrouve le tarif mentionne dans la brochure", Categorie.RAG),
    ("fais une synthese des avis clients du fichier", Categorie.RAG),
    ("trouve la definition de ce terme dans le glossaire", Categorie.RAG),
    ("quelles sections parlent de performance dans ce rapport ?", Categorie.RAG),
    ("cite les obligations du fournisseur dans ce contrat", Categorie.RAG),
    ("recherche les regles de teletravail dans le reglement", Categorie.RAG),
    ("quel est le numero de commande dans cette facture ?", Categorie.RAG),
    ("resume les changements annonces dans la note de version", Categorie.RAG),
    ("trouve les etapes d installation dans le guide utilisateur", Categorie.RAG),
    ("quelle reponse donne la FAQ sur les retours ?", Categorie.RAG),
    ("extrait les noms des participants de ce compte rendu", Categorie.RAG),
    ("cherche les contraintes techniques dans la specification", Categorie.RAG),

    # Conversation
    ("salut, ca va ?", Categorie.CONVERSATION),
    ("bonjour", Categorie.CONVERSATION),
    ("merci pour ton aide", Categorie.CONVERSATION),
    ("bonne journee", Categorie.CONVERSATION),
    ("comment vas-tu aujourd'hui ?", Categorie.CONVERSATION),
    ("bonsoir", Categorie.CONVERSATION),
    ("coucou", Categorie.CONVERSATION),
    ("enchanté de faire ta connaissance", Categorie.CONVERSATION),
    ("merci beaucoup", Categorie.CONVERSATION),
    ("a bientot", Categorie.CONVERSATION),
    ("bonne nuit", Categorie.CONVERSATION),
    ("quoi de neuf ?", Categorie.CONVERSATION),
    ("tu passes une bonne journee ?", Categorie.CONVERSATION),
    ("je suis content de te parler", Categorie.CONVERSATION),
    ("peux-tu me tenir compagnie ?", Categorie.CONVERSATION),
    ("ravi de te retrouver", Categorie.CONVERSATION),
    ("excuse-moi", Categorie.CONVERSATION),
    ("desole pour le derangement", Categorie.CONVERSATION),
    ("je te souhaite un bon weekend", Categorie.CONVERSATION),
    ("bonjour, tu es disponible ?", Categorie.CONVERSATION),
    ("comment se passe ta soiree ?", Categorie.CONVERSATION),
    ("merci, c est gentil", Categorie.CONVERSATION),
    ("salutations", Categorie.CONVERSATION),
    ("je voulais simplement dire bonjour", Categorie.CONVERSATION),
    ("passe une excellente journee", Categorie.CONVERSATION),
    ("a demain", Categorie.CONVERSATION),
    ("je m appelle Camille", Categorie.CONVERSATION),
    ("heureux de discuter avec toi", Categorie.CONVERSATION),
    ("bienvenue", Categorie.CONVERSATION),
    ("merci pour la reponse", Categorie.CONVERSATION),
    ("bonne continuation", Categorie.CONVERSATION),
    ("salut tout le monde", Categorie.CONVERSATION),
    ("je te laisse", Categorie.CONVERSATION),
    ("au revoir", Categorie.CONVERSATION),
    ("ca marche, merci", Categorie.CONVERSATION),
    ("comment puis-je t appeler ?", Categorie.CONVERSATION),
    ("j espere que tout va bien", Categorie.CONVERSATION),
    ("tres bonne journee a toi", Categorie.CONVERSATION),
    ("content de te voir", Categorie.CONVERSATION),
    ("bonjour assistant", Categorie.CONVERSATION),

    # Autre
    ("qui a gagne la coupe en 1998 ?", Categorie.AUTRE),
    ("quelle est la capitale du Japon ?", Categorie.AUTRE),
    ("donne-moi une recette de crepes", Categorie.AUTRE),
    ("quel temps fera-t-il demain ?", Categorie.AUTRE),
    ("raconte-moi une blague", Categorie.AUTRE),
    ("qui est le president de la France ?", Categorie.AUTRE),
    ("quelle est la population de Paris ?", Categorie.AUTRE),
    ("comment preparer des pates carbonara ?", Categorie.AUTRE),
    ("quelle musique ecouter pour travailler ?", Categorie.AUTRE),
    ("qui a ecrit Les Miserables ?", Categorie.AUTRE),
    ("conseille-moi un film de science-fiction", Categorie.AUTRE),
    ("quels pays bordent l Italie ?", Categorie.AUTRE),
    ("comment cultiver des tomates ?", Categorie.AUTRE),
    ("quelle est la hauteur de la tour Eiffel ?", Categorie.AUTRE),
    ("donne une idee de cadeau pour un anniversaire", Categorie.AUTRE),
    ("quand commence l ete ?", Categorie.AUTRE),
    ("qui a peint la Joconde ?", Categorie.AUTRE),
    ("quelles sont les regles du football ?", Categorie.AUTRE),
    ("comment nettoyer une tache de cafe ?", Categorie.AUTRE),
    ("pourquoi le ciel est bleu ?", Categorie.AUTRE),
    ("quelle langue parle-t-on au Bresil ?", Categorie.AUTRE),
    ("donne-moi des conseils pour dormir", Categorie.AUTRE),
    ("quel animal vit le plus longtemps ?", Categorie.AUTRE),
    ("comment organiser un voyage a Rome ?", Categorie.AUTRE),
    ("qui a invente le telephone ?", Categorie.AUTRE),
    ("quelle est la plus haute montagne du monde ?", Categorie.AUTRE),
    ("propose un menu vegetarien", Categorie.AUTRE),
    ("quels sont les symptomes de la grippe ?", Categorie.AUTRE),
    ("combien coute un billet de train pour Lyon ?", Categorie.AUTRE),
    ("quelle est la date de la fete nationale francaise ?", Categorie.AUTRE),
    ("comment choisir un velo ?", Categorie.AUTRE),
    ("qui a decouvert la penicilline ?", Categorie.AUTRE),
    ("quelle plante choisir pour un balcon ?", Categorie.AUTRE),
    ("comment fonctionne une voiture electrique ?", Categorie.AUTRE),
    ("quelle est la monnaie du Canada ?", Categorie.AUTRE),
    ("raconte une histoire pour enfant", Categorie.AUTRE),
    ("quelles sont les prochaines vacances scolaires ?", Categorie.AUTRE),
    ("comment prendre soin d un chat ?", Categorie.AUTRE),
    ("qui a compose La Flute enchantee ?", Categorie.AUTRE),
    ("donne-moi les actualites du jour", Categorie.AUTRE),
]

EXEMPLES.extend(
    (formulation.format(sujet=sujet), categorie)
    for categorie, formulations, sujets in (
        (
            Categorie.CODE,
            (
                "comment corriger ce probleme de {sujet} ?",
                "aide-moi a deboguer {sujet}",
                "pourquoi {sujet} ne fonctionne pas ?",
                "ecris un exemple de code pour {sujet}",
                "comment tester {sujet} ?",
                "peux-tu expliquer {sujet} en programmation ?",
                "quelle est la meilleure facon d implementer {sujet} ?",
                "comment optimiser {sujet} ?",
                "j ai une erreur avec {sujet}",
                "montre-moi comment configurer {sujet}",
            ),
            (
                "une boucle Python",
                "une requete SQL",
                "un composant React",
                "une API REST",
                "un conteneur Docker",
                "un test unitaire",
                "une migration de base de donnees",
                "un formulaire web",
                "un script Bash",
                "une authentification OAuth",
            ),
        ),
        (
            Categorie.MATH,
            (
                "calcule {sujet}",
                "quel est le resultat de {sujet} ?",
                "peux-tu resoudre {sujet} ?",
                "explique le calcul de {sujet}",
                "aide-moi avec {sujet}",
                "trouve la solution de {sujet}",
                "donne-moi le resultat exact de {sujet}",
                "comment calculer {sujet} ?",
                "verifie cette operation : {sujet}",
                "fais le calcul suivant : {sujet}",
            ),
            (
                "18 + 27",
                "56 - 19",
                "12 x 8",
                "144 / 12",
                "7 puissance 4",
                "la racine carree de 169",
                "35 pour cent de 480",
                "3x - 7 = 20",
                "la fraction 18 sur 24",
                "la moyenne de 6, 9 et 15",
            ),
        ),
        (
            Categorie.RAG,
            (
                "cherche {sujet} dans les documents fournis",
                "resume {sujet} a partir du dossier",
                "que disent les fichiers sur {sujet} ?",
                "extrais les informations sur {sujet} du document",
                "trouve le passage qui parle de {sujet}",
                "cite la section relative a {sujet}",
                "fais une synthese de {sujet} selon le rapport",
                "reponds en utilisant la documentation sur {sujet}",
                "liste les details concernant {sujet} dans le PDF",
                "retrouve {sujet} dans la base de connaissances",
            ),
            (
                "les conditions de paiement",
                "la politique de confidentialite",
                "la procedure de deploiement",
                "les criteres d acceptation",
                "les incidents recents",
                "le planning du projet",
                "les roles des participants",
                "la configuration du service",
                "les exigences de securite",
                "les modifications de la derniere version",
            ),
        ),
        (
            Categorie.CONVERSATION,
            (
                "bonjour {sujet}",
                "salut {sujet}",
                "bonsoir {sujet}",
                "merci {sujet}",
                "bonne journee {sujet}",
                "bonne soiree {sujet}",
                "heureux de discuter {sujet}",
                "content de te retrouver {sujet}",
                "je te souhaite une belle journee {sujet}",
                "a bientot {sujet}",
            ),
            (
                "assistant",
                "a toi",
                "avec toi",
                "aujourd hui",
                "pour ton aide",
                "et bienvenue",
                "comment vas-tu ?",
                "j espere que tu vas bien",
                "je suis la pour discuter",
                "on se reparle bientot",
            ),
        ),
        (
            Categorie.AUTRE,
            (
                "que sais-tu sur {sujet} ?",
                "donne-moi des conseils sur {sujet}",
                "quelle est la meilleure maniere de gerer {sujet} ?",
                "peux-tu m expliquer {sujet} ?",
                "propose une idee autour de {sujet}",
                "comment en savoir plus sur {sujet} ?",
                "raconte-moi quelque chose sur {sujet}",
                "quelle est ton opinion sur {sujet} ?",
                "aide-moi dans la vie quotidienne avec {sujet}",
                "donne des informations generales sur {sujet}",
            ),
            (
                "un voyage au Japon",
                "la cuisine vegetarienne",
                "le sommeil",
                "le jardinage",
                "un match de football",
                "la musique classique",
                "un budget personnel",
                "les films policiers",
                "une voiture electrique",
                "la preparation d un entretien",
            ),
        ),
    )
    for formulation in formulations
    for sujet in sujets
)

EXEMPLES.extend(
    (formulation.format(sujet=sujet), categorie)
    for categorie, formulations, sujets in (
        (
            Categorie.CODE,
            (
                "peux-tu generer du code pour {sujet} ?",
                "comment resoudre un bug dans {sujet} ?",
                "donne un tutoriel pour {sujet}",
                "quelle commande utiliser pour {sujet} ?",
                "aide-moi a refactoriser {sujet}",
                "comment deployer {sujet} ?",
            ),
            (
                "un projet Django",
                "une application Vue",
                "un service FastAPI",
                "un workflow GitHub Actions",
                "un schema Prisma",
                "un projet Kotlin",
                "une fonction Lambda",
                "un cache Redis",
                "une application Flutter",
                "un pipeline de donnees",
            ),
        ),
        (
            Categorie.MATH,
            (
                "determine {sujet}",
                "peux-tu demontrer {sujet} ?",
                "trouve la valeur de {sujet}",
                "resous ce probleme : {sujet}",
                "quelle methode appliquer a {sujet} ?",
                "detaille les etapes pour {sujet}",
            ),
            (
                "5y + 2 = 27",
                "le PPCM de 12 et 18",
                "la surface d un triangle de base 7 et hauteur 9",
                "la limite de 1 sur x quand x tend vers l infini",
                "la somme de 1 a 100",
                "le volume d un cylindre de rayon 3 et hauteur 8",
                "la variance de 2, 4, 6, 8",
                "la probabilite de deux faces avec deux pieces",
                "le determinant de la matrice 2 par 2",
                "la conversion de 3,5 kilometres en metres",
            ),
        ),
        (
            Categorie.RAG,
            (
                "dans les sources, retrouve {sujet}",
                "analyse les documents pour {sujet}",
                "quelle information trouve-t-on sur {sujet} ?",
                "fournis les extraits relatifs a {sujet}",
                "recherche {sujet} dans les pieces jointes",
                "base ta reponse sur les fichiers pour {sujet}",
            ),
            (
                "la date de livraison",
                "le budget approuve",
                "les mesures de conformite",
                "les contacts du support",
                "la marche a suivre en cas de panne",
                "les objectifs trimestriels",
                "les limitations du produit",
                "la duree de conservation des donnees",
                "les clauses de renouvellement",
                "les resultats du sondage",
            ),
        ),
        (
            Categorie.CONVERSATION,
            (
                "hello {sujet}",
                "coucou {sujet}",
                "merci beaucoup {sujet}",
                "ravi de faire ta connaissance {sujet}",
                "passe une bonne journee {sujet}",
                "au plaisir de te reparler {sujet}",
            ),
            (
                "mon ami",
                "assistant",
                "comment ca va",
                "pour ta disponibilite",
                "et a demain",
                "je suis heureux d etre ici",
                "tout simplement",
                "pour la discussion",
                "en cette belle journee",
                "on garde le contact",
            ),
        ),
        (
            Categorie.AUTRE,
            (
                "pourrais-tu me renseigner sur {sujet} ?",
                "quelles sont les bases de {sujet} ?",
                "a quoi sert {sujet} ?",
                "comment debuter avec {sujet} ?",
                "partage des astuces sur {sujet}",
                "que recommandes-tu pour {sujet} ?",
            ),
            (
                "la photographie",
                "la randonnee",
                "le cafe",
                "la lecture",
                "la natation",
                "le recyclage",
                "un repas de famille",
                "un demenagement",
                "la decoration interieure",
                "un cours de langue",
            ),
        ),
    )
    for formulation in formulations
    for sujet in sujets
)

EXEMPLES.extend(
    (formulation.format(sujet=sujet), categorie)
    for categorie, formulations, sujets in (
        (
            Categorie.CODE,
            (
                "comment concevoir {sujet} ?",
                "explique-moi l architecture de {sujet}",
                "quel exemple minimal peux-tu donner pour {sujet} ?",
                "comment diagnostiquer une panne sur {sujet} ?",
                "quelles bonnes pratiques appliquer a {sujet} ?",
                "ecris les tests necessaires pour {sujet}",
                "comment mettre en production {sujet} ?",
                "pourquoi la compilation de {sujet} echoue-t-elle ?",
                "aide-moi a securiser {sujet}",
                "comment mesurer les performances de {sujet} ?",
                "donne une implementation simple de {sujet}",
                "comment documenter {sujet} ?",
                "quelle erreur frequente faut-il eviter avec {sujet} ?",
                "comment ajouter des logs a {sujet} ?",
                "comment connecter {sujet} a une base de donnees ?",
                "aide-moi a relire le code de {sujet}",
                "comment gerer les exceptions dans {sujet} ?",
                "comment automatiser le deploiement de {sujet} ?",
                "comment organiser les fichiers de {sujet} ?",
                "quelle dependance faut-il installer pour {sujet} ?",
            ),
            (
                "un client HTTP Python",
                "une API GraphQL",
                "un tableau de bord React",
                "un microservice Go",
                "une application Android",
                "un site Next.js",
                "une fonction de recherche",
                "un bot Discord",
                "un systeme de paiement",
                "une file de messages RabbitMQ",
                "un schema PostgreSQL",
                "une tache planifiee Celery",
                "un serveur WebSocket",
                "un package npm",
                "un outil en ligne de commande",
                "une API Flask",
                "un formulaire Angular",
                "un service de cache",
                "un pipeline CI",
                "une application Spring",
            ),
        ),
        (
            Categorie.MATH,
            (
                "calcule {sujet}",
                "explique comment resoudre {sujet}",
                "donne la reponse a {sujet}",
                "detaille le raisonnement pour {sujet}",
                "quelle formule permet de traiter {sujet} ?",
                "verifie le resultat de {sujet}",
                "resous pas a pas {sujet}",
                "trouve une approximation de {sujet}",
                "peux-tu simplifier {sujet} ?",
                "comment representer {sujet} ?",
                "quel est le resultat numerique de {sujet} ?",
                "donne la solution mathematique de {sujet}",
                "aide-moi a comprendre {sujet}",
                "quelle est la methode la plus rapide pour {sujet} ?",
                "transforme {sujet}",
                "trouve la valeur inconnue dans {sujet}",
                "etablis le calcul pour {sujet}",
                "peux-tu illustrer {sujet} ?",
                "comment verifier {sujet} mentalement ?",
                "fais l exercice suivant : {sujet}",
            ),
            (
                "27 multiplie par 14",
                "le quotient de 125 par 5",
                "la somme de 42 et 58",
                "la difference entre 903 et 478",
                "l equation 4x plus 9 egal 37",
                "l equation x carre moins 16 egal zero",
                "25 pour cent de 360",
                "la racine cubique de 216",
                "le perimetre d un carre de cote 11",
                "l aire d un rectangle de 13 par 6",
                "le volume d une sphere de rayon 2",
                "la moyenne de 4, 8, 12 et 16",
                "la mediane de 1, 5, 7, 11 et 20",
                "le PGCD de 48 et 72",
                "le PPCM de 9 et 15",
                "la conversion de 180 degres en radians",
                "la probabilite de tirer un as",
                "la derivee de 3x au carre",
                "l integrale de x entre 1 et 4",
                "le logarithme naturel de e au carre",
            ),
        ),
        (
            Categorie.RAG,
            (
                "cherche {sujet} dans la documentation",
                "resume les sources concernant {sujet}",
                "retrouve la mention de {sujet} dans les fichiers",
                "cite le document qui traite de {sujet}",
                "extrais les passages sur {sujet}",
                "que contiennent les pieces jointes sur {sujet} ?",
                "fais une synthese documentaire de {sujet}",
                "identifie les informations relatives a {sujet}",
                "reponds depuis la base documentaire pour {sujet}",
                "liste les references associees a {sujet}",
                "dans quel document se trouve {sujet} ?",
                "analyse le dossier a propos de {sujet}",
                "releve les faits importants sur {sujet}",
                "compare les documents pour {sujet}",
                "trouve les consignes portant sur {sujet}",
                "cherche une preuve de {sujet} dans le rapport",
                "fournis les citations utiles pour {sujet}",
                "consulte le wiki pour {sujet}",
                "reformule ce que disent les documents sur {sujet}",
                "trouve le resume existant de {sujet}",
            ),
            (
                "le plan de reprise",
                "les seuils de qualite",
                "la politique de remboursement",
                "le processus de recrutement",
                "les droits des utilisateurs",
                "la liste des fournisseurs",
                "les livrables attendus",
                "le calendrier des formations",
                "les incidents de securite",
                "la configuration reseau",
                "le protocole de test",
                "les decisions de la reunion",
                "la procedure de facturation",
                "les conditions de garantie",
                "le niveau de service",
                "les regles de teletravail",
                "le suivi des risques",
                "les criteres de priorisation",
                "la feuille de route produit",
                "les changements contractuels",
            ),
        ),
        (
            Categorie.CONVERSATION,
            (
                "bonjour {sujet}",
                "salut {sujet}",
                "bonsoir {sujet}",
                "coucou {sujet}",
                "merci {sujet}",
                "merci beaucoup {sujet}",
                "bonne journee {sujet}",
                "bonne soiree {sujet}",
                "a bientot {sujet}",
                "au revoir {sujet}",
                "ravi de te parler {sujet}",
                "heureux de te retrouver {sujet}",
                "j espere que tu vas bien {sujet}",
                "je suis content de discuter {sujet}",
                "passe un bon weekend {sujet}",
                "je te souhaite le meilleur {sujet}",
                "c est gentil {sujet}",
                "avec plaisir {sujet}",
                "super, merci {sujet}",
                "prends soin de toi {sujet}",
            ),
            (
                "assistant",
                "mon ami",
                "comment vas-tu",
                "aujourd hui",
                "pour ton message",
                "pour ta reponse",
                "et merci encore",
                "on se reparle demain",
                "je suis de bonne humeur",
                "en cette matinee",
                "pour cette discussion",
                "tout simplement",
                "je suis la",
                "a toi aussi",
                "et bonne chance",
                "pour ton aide precieuse",
                "tu es tres aimable",
                "ca fait plaisir",
                "a la prochaine fois",
                "je te laisse maintenant",
            ),
        ),
        (
            Categorie.AUTRE,
            (
                "que peux-tu dire sur {sujet} ?",
                "donne-moi des idees pour {sujet}",
                "comment apprendre {sujet} ?",
                "quels conseils as-tu sur {sujet} ?",
                "peux-tu presenter {sujet} ?",
                "comment bien choisir {sujet} ?",
                "raconte-moi l histoire de {sujet}",
                "quelles sont les etapes pour {sujet} ?",
                "pourquoi s interesser a {sujet} ?",
                "quelle est une bonne approche de {sujet} ?",
                "fais une recommandation sur {sujet}",
                "quels sont les avantages de {sujet} ?",
                "comment se preparer a {sujet} ?",
                "quel materiel faut-il pour {sujet} ?",
                "donne une explication simple de {sujet}",
                "peux-tu comparer des options pour {sujet} ?",
                "quelles erreurs eviter pour {sujet} ?",
                "partage une information utile sur {sujet}",
                "comment planifier {sujet} ?",
                "quel est le meilleur moment pour {sujet} ?",
            ),
            (
                "un voyage en Espagne",
                "la cuisine thai",
                "la course a pied",
                "le yoga",
                "un potager urbain",
                "la guitare",
                "les echecs",
                "la peinture a l aquarelle",
                "un anniversaire surprise",
                "la gestion du stress",
                "un regime equilibre",
                "la protection solaire",
                "un chien adulte",
                "un chaton",
                "la photographie de nuit",
                "un sejour a la montagne",
                "la meditation",
                "un budget de vacances",
                "une fete entre amis",
                "la lecture rapide",
            ),
        ),
    )
    for formulation in formulations
    for sujet in sujets
)

X = [requete for requete, _ in EXEMPLES]
Y = [categorie for _, categorie in EXEMPLES]